package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseRes;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_res", primaryKey = "id")
public class Res extends BaseRes<Res> {
	
}
