package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_role", primaryKey = "id")
public class Role extends BaseRole<Role> {
	
}
