package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseRoleRes;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_role_res", primaryKey = "id")
public class RoleRes extends BaseRoleRes<RoleRes> {
	
}
