package io.jboot.b2c.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.b2c.service.entity.model.base.BaseProduct;

/**
 * Generated by Jboot.
 */
@Table(tableName = "b2c_product", primaryKey = "id")
public class Product extends BaseProduct<Product> {
	
}
