package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleRes<M extends BaseRoleRes<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "RoleRes:add";
    public static final String ACTION_DELETE = "RoleRes:delete";
    public static final String ACTION_UPDATE = "RoleRes:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setResId(java.lang.Long resId) {
		set("res_id", resId);
	}
	
	public java.lang.Long getResId() {
		return getLong("res_id");
	}

	public void setRoleId(java.lang.Long roleId) {
		set("role_id", roleId);
	}
	
	public java.lang.Long getRoleId() {
		return getLong("role_id");
	}

}
