package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLog<M extends BaseLog<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "Log:add";
    public static final String ACTION_DELETE = "Log:delete";
    public static final String ACTION_UPDATE = "Log:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setUid(java.lang.Long uid) {
		set("uid", uid);
	}
	
	public java.lang.Long getUid() {
		return getLong("uid");
	}

	public void setBrowser(java.lang.String browser) {
		set("browser", browser);
	}
	
	public java.lang.String getBrowser() {
		return getStr("browser");
	}

	public void setOperation(java.lang.String operation) {
		set("operation", operation);
	}
	
	public java.lang.String getOperation() {
		return getStr("operation");
	}

	public void setFrom(java.lang.String from) {
		set("from", from);
	}
	
	public java.lang.String getFrom() {
		return getStr("from");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setLastUpdAcct(java.lang.String lastUpdAcct) {
		set("lastUpdAcct", lastUpdAcct);
	}
	
	public java.lang.String getLastUpdAcct() {
		return getStr("lastUpdAcct");
	}

	public void setLastUpdTime(java.util.Date lastUpdTime) {
		set("lastUpdTime", lastUpdTime);
	}
	
	public java.util.Date getLastUpdTime() {
		return get("lastUpdTime");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}
	
	public java.lang.String getNote() {
		return getStr("note");
	}

}
